import { useSchemaStore } from './useSchemaStore';
import { useShallow } from 'zustand/react/shallow';

export function useEditorStoreSelectors() {
  return useSchemaStore(
    useShallow((s) => ({
      tables: s.tables,
      relations: s.relations,
      domains: s.domains,
      enums: s.enums,
      jsonSchemas: s.jsonSchemas,
      selectedTableId: s.selectedTableId,
      selectedTableIds: s.selectedTableIds,
      selectedRelation: s.selectedRelation,

      setSelectedTableId: s.setSelectedTableId,
      setSelectedRelation: s.setSelectedRelation,
      setSelectedTableIds: s.setSelectedTableIds,
      addTable: s.addTable,
      updateTablePosition: s.updateTablePosition,
      updateTableName: s.updateTableName,
      updateTableDescription: s.updateTableDescription,
      updateTableDomain: s.updateTableDomain,
      deleteTable: s.deleteTable,
      deleteTables: s.deleteTables,
      addField: s.addField,
      updateField: s.updateField,
      deleteField: s.deleteField,
      reorderField: s.reorderField,
      addRelation: s.addRelation,
      updateRelation: s.updateRelation,
      deleteRelation: s.deleteRelation,
      addDomain: s.addDomain,
      updateDomain: s.updateDomain,
      deleteDomain: s.deleteDomain,
      toggleTableSelection: s.toggleTableSelection,
      selectTablesInRect: s.selectTablesInRect,
      clearMultiSelection: s.clearMultiSelection,
      moveSelectedTables: s.moveSelectedTables,
      autoLayout: s.autoLayout,
      exportToFormat: s.exportToFormat,
      importFromFormat: s.importFromFormat,
      exportSelectionForClipboard: s.exportSelectionForClipboard,
      importSelectionFromClipboard: s.importSelectionFromClipboard,
      getTableColor: s.getTableColor,
      assignDomainToTables: s.assignDomainToTables,
      reorderDomains: s.reorderDomains,
      addEnum: s.addEnum,
      updateEnum: s.updateEnum,
      deleteEnum: s.deleteEnum,
      updateEnumPosition: s.updateEnumPosition,
      reorderEnumValues: s.reorderEnumValues,
      reorderEnums: s.reorderEnums,
      addJsonSchema: s.addJsonSchema,
      updateJsonSchema: s.updateJsonSchema,
      deleteJsonSchema: s.deleteJsonSchema,
      updateJsonSchemaPosition: s.updateJsonSchemaPosition,
      addJsonSchemaNode: s.addJsonSchemaNode,
      updateJsonSchemaNode: s.updateJsonSchemaNode,
      deleteJsonSchemaNode: s.deleteJsonSchemaNode,
      toggleJsonSchemaNodeCollapsed: s.toggleJsonSchemaNodeCollapsed,
      moveJsonSchemaNode: s.moveJsonSchemaNode,
      reorderJsonSchemas: s.reorderJsonSchemas,
      reorderTables: s.reorderTables,
      reorderSidebarEntities: s.reorderSidebarEntities,
      undo: s.undo,
      redo: s.redo,
      pushHistory: s.pushHistory,
      pastLength: s._past.length,
      futureLength: s._future.length,
    })),
  );
}
