import {
  Ban,
  Binary,
  Box,
  Braces,
  Calendar,
  Circle,
  Clock,
  Database,
  DollarSign,
  FileCode,
  Fingerprint,
  Globe,
  Hash,
  Hexagon,
  List,
  MapPin,
  Network,
  Ruler,
  Tag,
  ToggleLeft,
  Type,
  Zap,
} from 'lucide-react';

const FIELD_TYPE_ICONS: Record<string, React.ReactNode> = {
  uuid: <Fingerprint className="size-3.5" />,
  bigint: <Hash className="size-3.5" />,
  integer: <Hash className="size-3.5" />,
  smallint: <Hash className="size-3.5" />,
  serial: <Hash className="size-3.5" />,
  bigserial: <Hash className="size-3.5" />,
  varchar: <Type className="size-3.5" />,
  text: <Type className="size-3.5" />,
  citext: <Type className="size-3.5" />,
  boolean: <ToggleLeft className="size-3.5" />,
  timestamp: <Calendar className="size-3.5" />,
  timestamptz: <Calendar className="size-3.5" />,
  date: <Calendar className="size-3.5" />,
  time: <Clock className="size-3.5" />,
  interval: <Clock className="size-3.5" />,
  json: <Braces className="size-3.5" />,
  jsonb: <Braces className="size-3.5" />,
  decimal: <DollarSign className="size-3.5" />,
  numeric: <Hash className="size-3.5" />,
  real: <Hash className="size-3.5" />,
  'double precision': <Hash className="size-3.5" />,
  money: <DollarSign className="size-3.5" />,
  bytea: <Binary className="size-3.5" />,
  inet: <Globe className="size-3.5" />,
  cidr: <Network className="size-3.5" />,
  macaddr: <Hexagon className="size-3.5" />,
  point: <MapPin className="size-3.5" />,
  line: <Ruler className="size-3.5" />,
  polygon: <Box className="size-3.5" />,
  circle: <Circle className="size-3.5" />,
  xml: <FileCode className="size-3.5" />,
  array: <List className="size-3.5" />,
  enum: <Tag className="size-3.5" />,
  vector: <Zap className="size-3.5" />,
  string: <Type className="size-3.5" />,
  number: <Hash className="size-3.5" />,
  object: <Braces className="size-3.5" />,
  Boolean: <ToggleLeft className="size-3.5" />,
  Integer: <Hash className="size-3.5" />,
  Real: <Hash className="size-3.5" />,
  String: <Type className="size-3.5" />,
  UnlimitedNatural: <Hash className="size-3.5" />,
  Date: <Calendar className="size-3.5" />,
  DateTime: <Calendar className="size-3.5" />,
  Object: <Braces className="size-3.5" />,
  Collection: <List className="size-3.5" />,
  List: <List className="size-3.5" />,
  Set: <List className="size-3.5" />,
  Map: <Braces className="size-3.5" />,
  Result: <Database className="size-3.5" />,
  literal: <Tag className="size-3.5" />,
  null: <Ban className="size-3.5" />,
  void: <Ban className="size-3.5" />,
};

export function getDataTypeIcon(type: string) {
  return FIELD_TYPE_ICONS[type] || <Database className="size-3.5" />;
}
