FROM node:22-alpine AS base
WORKDIR /app

COPY package*.json ./
COPY apps/api/package*.json ./apps/api/
COPY packages/api-client/package*.json ./packages/api-client/
RUN npm ci

COPY . .
RUN npm run api:build

WORKDIR /app/apps/api
EXPOSE 3200
CMD ["node", "dist/src/main.js"]
