import type { SchemaSerializer } from './types';
import type { Schema, Table, Field, FieldType, Relation, Domain } from '../../model/types';

export const ddlSerializer: SchemaSerializer = {
  id: 'postgresql',
  name: 'PostgreSQL DDL',
  description: 'Export/import PostgreSQL Data Definition Language',
  fileExtension: '.sql',
  mimeType: 'text/plain',
  canImport: true,
  canExport: true,

  serialize(schema: Schema): string {
    let ddl = '-- PostgreSQL Schema\n-- Generated by drawSQL\n\n';

    schema.tables.forEach(table => {
      const schemaPrefix = table.schema ? `${table.schema}.` : '';
      // Table description as comment before CREATE TABLE
      if (table.description) {
        table.description.split('\n').forEach(line => {
          ddl += `-- ${line}\n`;
        });
      }
      ddl += `CREATE TABLE ${schemaPrefix}${table.name} (\n`;
      const fieldDefs = table.fields.map(field => {
        let def = `  ${field.name} ${mapTypeToSQL(field.type)}`;
        if (field.isPrimaryKey) def += ' PRIMARY KEY';
        if (!field.isNullable && !field.isPrimaryKey) def += ' NOT NULL';
        if (field.isUnique && !field.isPrimaryKey) def += ' UNIQUE';
        if (field.defaultValue) def += ` DEFAULT ${field.defaultValue}`;
        return def;
      });
      ddl += fieldDefs.join(',\n');
      ddl += '\n);\n\n';
    });

    // Foreign keys
    schema.relations.forEach(rel => {
      const fromTable = schema.tables.find(t => t.id === rel.fromTableId);
      const toTable = schema.tables.find(t => t.id === rel.toTableId);
      const fromField = fromTable?.fields.find(f => f.id === rel.fromFieldId);
      const toField = toTable?.fields.find(f => f.id === rel.toFieldId);

      if (fromTable && toTable && fromField && toField) {
        ddl += `ALTER TABLE ${fromTable.name}\n`;
        ddl += `  ADD CONSTRAINT fk_${fromTable.name}_${toTable.name}\n`;
        ddl += `  FOREIGN KEY (${fromField.name})\n`;
        ddl += `  REFERENCES ${toTable.name}(${toField.name});\n\n`;
      }
    });

    return ddl;
  },

  deserialize(content: string): { tables: Table[]; relations: Relation[]; domains?: Domain[] } {
    const tables: Table[] = [];
    const relations: Relation[] = [];
    const tableMap = new Map<string, Table>();
    let tableIndex = 0;
    let _idSeq = 0;
    const uid = (prefix: string) => `${prefix}_${Date.now()}_${(++_idSeq).toString(36)}_${Math.random().toString(36).slice(2, 6)}`;

    // Parse CREATE TABLE statements
    const createTableRegex = /CREATE\s+TABLE\s+(?:IF\s+NOT\s+EXISTS\s+)?(?:(\w+)\.)?(\w+)\s*\(([\s\S]*?)\);/gi;
    let match: RegExpExecArray | null;

    while ((match = createTableRegex.exec(content)) !== null) {
      const schemaName = match[1] || 'public';
      const tableName = match[2];
      const columnsBlock = match[3];

      // Extract comment block before this CREATE TABLE
      const beforeCreate = content.substring(0, match.index);
      const commentLines: string[] = [];
      const linesBeforeArr = beforeCreate.split('\n');
      // Walk backward from the end to collect contiguous -- comments
      for (let i = linesBeforeArr.length - 1; i >= 0; i--) {
        const trimmed = linesBeforeArr[i].trim();
        if (trimmed.startsWith('--')) {
          commentLines.unshift(trimmed.replace(/^--\s?/, ''));
        } else if (trimmed === '') {
          // skip empty lines between comments and CREATE
          continue;
        } else {
          break;
        }
      }
      // Filter out generic header comments
      const description = commentLines
        .filter(l => !l.startsWith('PostgreSQL Schema') && !l.startsWith('Generated by'))
        .join('\n')
        .trim();

      const fields: Field[] = [];
      // Split by commas that are not inside parentheses
      const lines: string[] = [];
      let depth = 0;
      let current = '';
      for (let i = 0; i < columnsBlock.length; i++) {
        const ch = columnsBlock[i];
        if (ch === '(') depth++;
        else if (ch === ')') depth--;
        else if (ch === ',' && depth === 0) {
          lines.push(current.trim());
          current = '';
          continue;
        }
        current += ch;
      }
      if (current.trim()) lines.push(current.trim());

      for (const line of lines) {
        // Skip constraints
        if (/^\s*(CONSTRAINT|PRIMARY\s+KEY\s*\(|FOREIGN\s+KEY|UNIQUE\s*\(|CHECK\s*\(|INDEX)/i.test(line)) continue;

        // Match column name and type - be permissive, then parse modifiers from the rest
        const colMatch = line.match(/^\s*(\w+)\s+(\w+(?:\s*\([^)]*\))?(?:\s+(?:varying|precision|without\s+time\s+zone|with\s+time\s+zone))?)/i);
        if (colMatch) {
          const colName = colMatch[1];
          // Skip if column name is a reserved keyword used as constraint
          if (/^(constraint|primary|foreign|unique|check|index|exclude)$/i.test(colName)) continue;

          const colType = parseFieldType(colMatch[2].trim());
          const rest = line.toUpperCase();

          const hasReferences = /REFERENCES\s+/i.test(line);

          fields.push({
            id: uid(`${tableName}_${colName}`),
            name: colName,
            type: colType,
            isPrimaryKey: rest.includes('PRIMARY KEY'),
            isNullable: !rest.includes('NOT NULL') && !rest.includes('PRIMARY KEY'),
            isForeignKey: hasReferences,
            isUnique: rest.includes('UNIQUE'),
          });
        }
      }

      const table: Table = {
        id: uid(`table_${tableName}`),
        name: tableName,
        description: description || undefined,
        schema: schemaName,
        fields,
        position: { x: 100 + (tableIndex % 4) * 320, y: 100 + Math.floor(tableIndex / 4) * 300 },
      };

      tables.push(table);
      tableMap.set(tableName, table);
      tableIndex++;
    }

    // Parse ALTER TABLE ... ADD FOREIGN KEY
    const fkRegex = /ALTER\s+TABLE\s+(?:\w+\.)?(\w+)\s+ADD\s+CONSTRAINT\s+\w+\s+FOREIGN\s+KEY\s*\((\w+)\)\s*REFERENCES\s+(?:\w+\.)?(\w+)\s*\((\w+)\)/gi;

    while ((match = fkRegex.exec(content)) !== null) {
      const fromTableName = match[1];
      const fromFieldName = match[2];
      const toTableName = match[3];
      const toFieldName = match[4];

      const fromTable = tableMap.get(fromTableName);
      const toTable = tableMap.get(toTableName);

      if (fromTable && toTable) {
        const fromField = fromTable.fields.find(f => f.name === fromFieldName);
        const toField = toTable.fields.find(f => f.name === toFieldName);

        if (fromField && toField) {
          fromField.isForeignKey = true;
          fromField.foreignKeyTable = toTableName;
          fromField.foreignKeyField = toFieldName;

          relations.push({
            id: uid('rel'),
            fromTableId: fromTable.id,
            fromFieldId: fromField.id,
            toTableId: toTable.id,
            toFieldId: toField.id,
            type: '1:N',
          });
        }
      }
    }

    // Also parse inline REFERENCES within CREATE TABLE columns
    for (const table of tables) {
      for (const field of table.fields) {
        if (field.isForeignKey && !field.foreignKeyTable) {
          // Try to find REFERENCES in the original column definition
          const inlineRefRegex = new RegExp(
            `${field.name}\\s+\\w+.*?REFERENCES\\s+(?:\\w+\\.)?(\\w+)\\s*\\((\\w+)\\)`,
            'i'
          );
          const inlineMatch = content.match(inlineRefRegex);
          if (inlineMatch) {
            const refTableName = inlineMatch[1];
            const refFieldName = inlineMatch[2];
            const refTable = tableMap.get(refTableName);
            if (refTable) {
              const refField = refTable.fields.find(f => f.name === refFieldName);
              if (refField) {
                field.foreignKeyTable = refTableName;
                field.foreignKeyField = refFieldName;
                relations.push({
                  id: uid('rel'),
                  fromTableId: table.id,
                  fromFieldId: field.id,
                  toTableId: refTable.id,
                  toFieldId: refField.id,
                  type: '1:N',
                });
              }
            }
          }
        }
      }
    }

    return { tables, relations };
  },
};

function mapTypeToSQL(type: FieldType): string {
  const map: Record<string, string> = {
    'uuid': 'UUID',
    'bigint': 'BIGINT',
    'integer': 'INTEGER',
    'smallint': 'SMALLINT',
    'serial': 'SERIAL',
    'bigserial': 'BIGSERIAL',
    'varchar': 'VARCHAR(255)',
    'text': 'TEXT',
    'citext': 'CITEXT',
    'boolean': 'BOOLEAN',
    'timestamp': 'TIMESTAMP',
    'timestamptz': 'TIMESTAMPTZ',
    'date': 'DATE',
    'time': 'TIME',
    'json': 'JSON',
    'jsonb': 'JSONB',
    'decimal': 'DECIMAL',
    'numeric': 'NUMERIC',
    'real': 'REAL',
    'double precision': 'DOUBLE PRECISION',
    'bytea': 'BYTEA',
    'inet': 'INET',
    'cidr': 'CIDR',
    'macaddr': 'MACADDR',
    'interval': 'INTERVAL',
    'point': 'POINT',
    'line': 'LINE',
    'polygon': 'POLYGON',
    'circle': 'CIRCLE',
    'money': 'MONEY',
    'xml': 'XML',
    'array': 'TEXT[]',
    'vector': 'VECTOR',
    'enum': 'TEXT',
  };
  return map[type] || type.toUpperCase();
}

function parseFieldType(sqlType: string): FieldType {
  const normalized = sqlType.toLowerCase().replace(/\(.*\)/, '').trim();
  const map: Record<string, FieldType> = {
    'uuid': 'uuid',
    'bigint': 'bigint',
    'int8': 'bigint',
    'integer': 'integer',
    'int': 'integer',
    'int4': 'integer',
    'smallint': 'smallint',
    'int2': 'smallint',
    'serial': 'serial',
    'serial4': 'serial',
    'bigserial': 'bigserial',
    'serial8': 'bigserial',
    'varchar': 'varchar',
    'character varying': 'varchar',
    'text': 'text',
    'citext': 'citext',
    'boolean': 'boolean',
    'bool': 'boolean',
    'timestamp': 'timestamp',
    'timestamp without time zone': 'timestamp',
    'timestamptz': 'timestamptz',
    'timestamp with time zone': 'timestamptz',
    'date': 'date',
    'time': 'time',
    'json': 'json',
    'jsonb': 'jsonb',
    'decimal': 'decimal',
    'numeric': 'numeric',
    'real': 'real',
    'float4': 'real',
    'double precision': 'double precision',
    'float8': 'double precision',
    'bytea': 'bytea',
    'inet': 'inet',
    'cidr': 'cidr',
    'macaddr': 'macaddr',
    'interval': 'interval',
    'point': 'point',
    'line': 'line',
    'polygon': 'polygon',
    'circle': 'circle',
    'money': 'money',
    'xml': 'xml',
    'vector': 'vector',
  };
  return map[normalized] || 'text';
}
