import type { SchemaSerializer } from './types';
import type { Schema, Table, Field, Relation, FieldType } from '../../model/types';

/**
 * Supabase RLS Policies Serializer
 *
 * Export: generates full SQL with helper functions, RLS enabling, and policies
 *         based on the visual schema (tables, columns, FK relations).
 *
 * Import: parses Supabase RLS SQL and reconstructs:
 *   - Tables from `alter table ... enable row level security`
 *   - Columns from policy bodies and helper functions
 *   - FK relations from helper functions, policy bodies, and column naming conventions
 */
export const supabaseRlsSerializer: SchemaSerializer = {
  id: 'supabase-rls',
  name: 'Supabase RLS',
  description: 'Supabase Row Level Security policies with helper functions',
  fileExtension: '.sql',
  mimeType: 'text/plain',
  canImport: true,
  canExport: true,

  serialize(schema: Schema): string {
    const lines: string[] = [];

    lines.push('-- =========================================================');
    lines.push('-- Supabase RLS policies');
    lines.push('-- Generated by drawSQL');
    lines.push('-- Assumption: public.users.id = auth.uid()');
    lines.push('-- =========================================================');
    lines.push('');

    // 0. Safety
    lines.push('-- ---------------------------');
    lines.push('-- 0. Safety');
    lines.push('-- ---------------------------');
    lines.push('set search_path = public;');
    lines.push('');

    // 1. Build dependency graph to create helper functions
    const fkMap = buildFkMap(schema);
    const helperFunctions = generateHelperFunctions(schema, fkMap);

    if (helperFunctions.length > 0) {
      lines.push('-- ---------------------------');
      lines.push('-- 1. Helper functions');
      lines.push('-- ---------------------------');
      lines.push('');
      lines.push(...helperFunctions);
    }

    // 2. Enable RLS
    lines.push('-- ---------------------------');
    lines.push('-- 2. Enable RLS');
    lines.push('-- ---------------------------');
    lines.push('');
    schema.tables.forEach(table => {
      lines.push(`alter table public.${table.name} enable row level security;`);
    });
    lines.push('');

    // 3. Policies per table
    let sectionNum = 3;
    schema.tables.forEach(table => {
      lines.push('-- ---------------------------');
      lines.push(`-- ${sectionNum}. ${table.name.toUpperCase()}`);
      lines.push('-- ---------------------------');
      lines.push('');

      const accessExpr = getAccessExpression(table, schema, fkMap);
      const isUserTable = table.name === 'users';
      const isRefTable = isReferenceTable(table, schema);

      if (isUserTable) {
        lines.push(...generateSelfAccessPolicies(table.name));
      } else if (isRefTable) {
        lines.push(...generateReadOnlyPolicies(table.name));
      } else {
        lines.push(...generateStandardPolicies(table.name, accessExpr));
      }

      lines.push('');
      sectionNum++;
    });

    return lines.join('\n');
  },

  deserialize(content: string): Schema {
    const tables: Table[] = [];
    const relations: Relation[] = [];
    const tableMap = new Map<string, Table>();

    // Unified column registry: tableName → Set<columnName>
    const tableColumns = new Map<string, Set<string>>();
    const ensureCols = (t: string) => {
      if (!tableColumns.has(t)) tableColumns.set(t, new Set());
      return tableColumns.get(t)!;
    };

    // ──────────────────────────────────
    // 1. Extract table names from `alter table public.X enable row level security`
    // ──────────────────────────────────
    const tableNames: string[] = [];
    const rlsRegex = /alter\s+table\s+(?:public\.)?(\w+)\s+enable\s+row\s+level\s+security/gi;
    let match: RegExpExecArray | null;

    while ((match = rlsRegex.exec(content)) !== null) {
      const name = match[1];
      if (!tableNames.includes(name)) {
        tableNames.push(name);
        ensureCols(name);
      }
    }

    // ──────────────────────────────────
    // 2. Parse ALL function bodies to discover table→column mappings
    //    and extract FK relationships from JOINs and WHERE clauses
    // ──────────────────────────────────
    interface ParsedRelation {
      fromTable: string;
      fromColumn: string;
      toTable: string;
      toColumn: string;
    }
    const discoveredRelations: ParsedRelation[] = [];

    // Match all function bodies between $$ ... $$
    const allFuncRegex = /function\s+(?:public\.)?(\w+)\s*\([^)]*\)[\s\S]*?as\s*\$\$\s*([\s\S]*?)\$\$/gi;

    while ((match = allFuncRegex.exec(content)) !== null) {
      const funcName = match[1];
      const body = match[2];

      // Extract alias.column patterns → discover columns for tables
      // Pattern: FROM public.table_name alias
      const fromAliasRegex = /from\s+(?:public\.)?(\w+)\s+(\w+)/gi;
      const aliasToTable = new Map<string, string>();
      let fMatch;

      while ((fMatch = fromAliasRegex.exec(body)) !== null) {
        aliasToTable.set(fMatch[2], fMatch[1]);
      }

      // Pattern: JOIN public.table_name alias ON ...
      const joinAliasRegex = /join\s+(?:public\.)?(\w+)\s+(\w+)\s+on\s+(\w+)\.(\w+)\s*=\s*(\w+)\.(\w+)/gi;

      while ((fMatch = joinAliasRegex.exec(body)) !== null) {
        const joinTable = fMatch[1];
        const joinAlias = fMatch[2];
        const leftAlias = fMatch[3];
        const leftCol = fMatch[4];
        const rightAlias = fMatch[5];
        const rightCol = fMatch[6];

        aliasToTable.set(joinAlias, joinTable);

        // Resolve the join condition to actual table names
        const leftTable = aliasToTable.get(leftAlias);
        const rightTable = aliasToTable.get(rightAlias);

        if (leftTable && rightTable) {
          ensureCols(leftTable).add(leftCol);
          ensureCols(rightTable).add(rightCol);

          // The join tells us: one column references the other
          // Convention: alias.id = other_alias.fk_col means fk_col → id
          if (leftCol === 'id') {
            discoveredRelations.push({
              fromTable: rightTable,
              fromColumn: rightCol,
              toTable: leftTable,
              toColumn: leftCol,
            });
          } else if (rightCol === 'id') {
            discoveredRelations.push({
              fromTable: leftTable,
              fromColumn: leftCol,
              toTable: rightTable,
              toColumn: rightCol,
            });
          }
        }
      }

      // Extract all alias.column references in the body
      const aliasColRegex = /(\w+)\.(\w+)/g;
      while ((fMatch = aliasColRegex.exec(body)) !== null) {
        const alias = fMatch[1];
        const col = fMatch[2];
        // Skip: public.table_name, auth.uid()
        if (alias === 'public' || alias === 'auth') continue;
        const tableName = aliasToTable.get(alias);
        if (tableName) {
          ensureCols(tableName).add(col);
        }
      }

      // For workspace_id_for_X functions with no JOINs:
      // Pattern: SELECT alias.workspace_id FROM table alias WHERE alias.id = _param
      // This means: table.workspace_id → references workspaces
      if (funcName.startsWith('workspace_id_for_') && !body.match(/join/i)) {
        const simpleMatch = body.match(
          /select\s+(\w+)\.(\w+)\s+from\s+(?:public\.)?(\w+)\s+(\w+)\s+where\s+\w+\.(\w+)\s*=\s*_/i
        );
        if (simpleMatch) {
          const tableName = simpleMatch[3];
          const selectCol = simpleMatch[2]; // e.g. workspace_id
          const whereCol = simpleMatch[5]; // e.g. id

          ensureCols(tableName).add(selectCol);
          ensureCols(tableName).add(whereCol);

          // workspace_id → references workspaces (if exists)
          if (selectCol.endsWith('_id')) {
            const refTable = guessReferencedTable(selectCol, tableNames);
            if (refTable) {
              discoveredRelations.push({
                fromTable: tableName,
                fromColumn: selectCol,
                toTable: refTable,
                toColumn: 'id',
              });
            }
          }
        }
      }
    }

    // ──────────────────────────────────
    // 3. Parse policy bodies to extract column references
    // ──────────────────────────────────
    // Split content into individual policy blocks
    const policyBlockRegex =
      /create\s+policy\s+"([^"]+)"\s+on\s+(?:public\.)?(\w+)\s+([\s\S]*?)(?=;\s*(?:drop\s+policy|create\s+policy|alter\s+table|--\s*--))/gi;

    while ((match = policyBlockRegex.exec(content)) !== null) {
      const tableName = match[2];
      const policyBody = match[3];
      const cols = ensureCols(tableName);

      // column = auth.uid()
      for (const m of policyBody.matchAll(/(\w+)\s*=\s*auth\.uid\(\)/gi)) {
        cols.add(m[1]);
      }

      // is_workspace_member(column) — direct call, not nested
      for (const m of policyBody.matchAll(/is_workspace_member\((\w+)\)/gi)) {
        const col = m[1];
        if (col !== 'public') cols.add(col);
      }

      // has_workspace_role(column, ...) — direct call, not nested
      for (const m of policyBody.matchAll(/has_workspace_role\((\w+)\s*,/gi)) {
        const col = m[1];
        if (col !== 'public') cols.add(col);
      }

      // workspace_id_for_X(column) — always a direct column reference
      for (const m of policyBody.matchAll(/\w+_for_\w+\((\w+)\)/gi)) {
        cols.add(m[1]);
      }

      // Also detect: public.workspace_id_for_X(column) — the argument is a column of THIS table
      for (const m of policyBody.matchAll(/(?:public\.)?\w+_for_\w+\((\w+)\)/gi)) {
        cols.add(m[1]);
      }
    }

    // ──────────────────────────────────
    // 4. Also extract columns from nested helper calls in policies
    //    Pattern: is_workspace_member(public.workspace_id_for_X(column))
    //    We already extract `column` above. But also need to recognize
    //    that the outer function call's argument references workspace through a chain.
    // ──────────────────────────────────
    // (Already handled in step 3)

    // ──────────────────────────────────
    // 5. Build tables with discovered columns
    // ─────────────────────────────────
    const TABLE_COLORS = [
      '#ef4444', '#6366f1', '#8b5cf6', '#3b82f6', '#10b981',
      '#f59e0b', '#ec4899', '#14b8a6', '#f97316', '#06b6d4',
      '#84cc16', '#a855f7', '#e11d48', '#0ea5e9', '#22c55e',
    ];

    let idCounter = 1;
    const nextId = (prefix: string) => `${prefix}_${idCounter++}_${Date.now()}`;

    let tableIndex = 0;
    for (const name of tableNames) {
      const cols = tableColumns.get(name) || new Set<string>();

      // Always ensure an id column exists
      cols.add('id');

      // Add common timestamp columns
      cols.add('created_at');
      cols.add('updated_at');

      const fields: Field[] = [];

      // Sort columns: PK first, then FKs, then others
      const colArray = Array.from(cols);
      colArray.sort((a, b) => {
        const aIsPk = a === 'id';
        const bIsPk = b === 'id';
        if (aIsPk && !bIsPk) return -1;
        if (!aIsPk && bIsPk) return 1;

        const aIsFk = a.endsWith('_id');
        const bIsFk = b.endsWith('_id');
        if (aIsFk && !bIsFk) return -1;
        if (!aIsFk && bIsFk) return 1;

        return a.localeCompare(b);
      });

      for (const colName of colArray) {
        // Determine if this is a PK for THIS table
        const singular = name.replace(/s$/, '');
        const isPk =
          colName === 'id' ||
          colName === `${name}_id` ||
          colName === `${singular}_id`;

        const isFk = colName.endsWith('_id') && !isPk;
        const colType = guessColumnType(colName);
        const foreignKeyTable = isFk ? guessReferencedTable(colName, tableNames) : undefined;

        fields.push({
          id: nextId(`${name}_${colName}`),
          name: colName,
          type: colType,
          isPrimaryKey: isPk,
          isNullable: !isPk,
          isForeignKey: isFk,
          foreignKeyTable,
          foreignKeyField: isFk ? 'id' : undefined,
        });
      }

      const table: Table = {
        id: nextId(`table_${name}`),
        name,
        schema: 'public',
        fields,
        position: {
          x: 100 + (tableIndex % 4) * 350,
          y: 100 + Math.floor(tableIndex / 4) * 320,
        },
        color: TABLE_COLORS[tableIndex % TABLE_COLORS.length],
      };

      tables.push(table);
      tableMap.set(name, table);
      tableIndex++;
    }

    // ──────────────────────────────────
    // 6. Build relations
    // ──────────────────────────────────

    // Helper to find a field in a table by column name
    const findField = (table: Table, colName: string): Field | undefined =>
      table.fields.find(f => f.name === colName);

    // Track created relations to avoid duplicates
    const relationKeys = new Set<string>();
    const addRelation = (
      fromTable: Table,
      fromField: Field,
      toTable: Table,
      toField: Field,
    ) => {
      const key = `${fromTable.id}:${fromField.id}->${toTable.id}:${toField.id}`;
      const reverseKey = `${toTable.id}:${toField.id}->${fromTable.id}:${fromField.id}`;
      if (relationKeys.has(key) || relationKeys.has(reverseKey)) return;
      relationKeys.add(key);

      relations.push({
        id: nextId('rel'),
        fromTableId: fromTable.id,
        fromFieldId: fromField.id,
        toTableId: toTable.id,
        toFieldId: toField.id,
        type: '1:N',
      });
    };

    // 6a. Relations from FK columns (based on naming convention)
    for (const table of tables) {
      for (const field of table.fields) {
        if (field.isForeignKey && field.foreignKeyTable) {
          const targetTable = tableMap.get(field.foreignKeyTable);
          if (targetTable) {
            const targetField =
              findField(targetTable, field.foreignKeyField || 'id') ||
              targetTable.fields.find(f => f.isPrimaryKey) ||
              findField(targetTable, 'id');

            if (targetField) {
              addRelation(table, field, targetTable, targetField);
            }
          }
        }
      }
    }

    // 6b. Relations from helper function analysis
    for (const rel of discoveredRelations) {
      const fromTable = tableMap.get(rel.fromTable);
      const toTable = tableMap.get(rel.toTable);
      if (!fromTable || !toTable) continue;

      const fromField = findField(fromTable, rel.fromColumn);
      const toField = findField(toTable, rel.toColumn);
      if (!fromField || !toField) continue;

      addRelation(fromTable, fromField, toTable, toField);
    }

    return { tables, relations };
  },
};

// ──────────────────────────────────
// Helper utilities for EXPORT
// ──────────────────────────────────

interface FkInfo {
  fromTable: string;
  fromField: string;
  toTable: string;
  toField: string;
}

function buildFkMap(schema: Schema): FkInfo[] {
  const fks: FkInfo[] = [];
  for (const rel of schema.relations) {
    const fromTable = schema.tables.find(t => t.id === rel.fromTableId);
    const toTable = schema.tables.find(t => t.id === rel.toTableId);
    const fromField = fromTable?.fields.find(f => f.id === rel.fromFieldId);
    const toField = toTable?.fields.find(f => f.id === rel.toFieldId);

    if (fromTable && toTable && fromField && toField) {
      fks.push({
        fromTable: fromTable.name,
        fromField: fromField.name,
        toTable: toTable.name,
        toField: toField.name,
      });
    }
  }
  return fks;
}

function generateHelperFunctions(schema: Schema, fks: FkInfo[]): string[] {
  const lines: string[] = [];

  const hasMembership = schema.tables.some(t =>
    t.name === 'workspace_members' || t.name.endsWith('_members')
  );

  if (hasMembership) {
    const memberTable = schema.tables.find(t =>
      t.name === 'workspace_members' || t.name.endsWith('_members')
    );
    if (memberTable) {
      const workspaceCol = memberTable.fields.find(f => f.name === 'workspace_id')?.name || 'workspace_id';
      const userCol = memberTable.fields.find(f => f.name === 'user_id')?.name || 'user_id';

      lines.push(`create or replace function public.is_workspace_member(_workspace_id uuid)`);
      lines.push(`returns boolean`);
      lines.push(`language sql`);
      lines.push(`stable`);
      lines.push(`security definer`);
      lines.push(`set search_path = public`);
      lines.push(`as $$`);
      lines.push(`  select exists (`);
      lines.push(`    select 1`);
      lines.push(`    from public.${memberTable.name} wm`);
      lines.push(`    where wm.${workspaceCol} = _workspace_id`);
      lines.push(`      and wm.${userCol} = auth.uid()`);
      lines.push(`  );`);
      lines.push(`$$;`);
      lines.push('');

      const hasRole = memberTable.fields.some(f => f.name === 'role');
      if (hasRole) {
        lines.push(`create or replace function public.has_workspace_role(_workspace_id uuid, _roles text[])`);
        lines.push(`returns boolean`);
        lines.push(`language sql`);
        lines.push(`stable`);
        lines.push(`security definer`);
        lines.push(`set search_path = public`);
        lines.push(`as $$`);
        lines.push(`  select exists (`);
        lines.push(`    select 1`);
        lines.push(`    from public.${memberTable.name} wm`);
        lines.push(`    where wm.${workspaceCol} = _workspace_id`);
        lines.push(`      and wm.${userCol} = auth.uid()`);
        lines.push(`      and wm.role = any(_roles)`);
        lines.push(`  );`);
        lines.push(`$$;`);
        lines.push('');
      }
    }
  }

  const workspaceTable = schema.tables.find(t => t.name === 'workspaces');
  if (workspaceTable) {
    const tablesWithWorkspace = schema.tables.filter(t =>
      t.fields.some(f => f.name === 'workspace_id') && t.name !== 'workspaces' && t.name !== 'workspace_members'
    );

    for (const table of tablesWithWorkspace) {
      if (table.name === 'workspaces') continue;

      const childFks = fks.filter(fk => fk.toTable === table.name);

      for (const childFk of childFks) {
        const childTable = schema.tables.find(t => t.name === childFk.fromTable);
        if (childTable && !childTable.fields.some(f => f.name === 'workspace_id')) {
          lines.push(generateWorkspaceIdForFunction(
            childTable.name,
            childFk.fromField,
            table.name
          ));
        }
      }
    }
  }

  return lines;
}

function generateWorkspaceIdForFunction(
  childTable: string,
  fkColumn: string,
  parentTable: string
): string {
  const funcName = `workspace_id_for_${childTable.replace(/s$/, '')}`;
  const paramName = `_${childTable.replace(/s$/, '')}_id`;

  return [
    `create or replace function public.${funcName}(${paramName} uuid)`,
    `returns uuid`,
    `language sql`,
    `stable`,
    `security definer`,
    `set search_path = public`,
    `as $$`,
    `  select b.workspace_id`,
    `  from public.${childTable} t`,
    `  join public.${parentTable} b on b.id = t.${fkColumn}`,
    `  where t.id = ${paramName}`,
    `  limit 1;`,
    `$$;`,
    '',
  ].join('\n');
}

function getAccessExpression(
  table: Table,
  schema: Schema,
  fks: FkInfo[]
): string {
  if (table.fields.some(f => f.name === 'workspace_id')) {
    return 'public.is_workspace_member(workspace_id)';
  }

  for (const fk of fks) {
    if (fk.fromTable === table.name) {
      const parentTable = schema.tables.find(t => t.name === fk.toTable);
      if (parentTable?.fields.some(f => f.name === 'workspace_id')) {
        const singular = table.name.replace(/s$/, '');
        return `public.is_workspace_member(public.workspace_id_for_${singular}(${fk.fromField}))`;
      }
    }
  }

  return 'true';
}

function isReferenceTable(table: Table, schema: Schema): boolean {
  const hasWorkspaceRef = table.fields.some(f =>
    f.name === 'workspace_id' || f.name === 'user_id'
  );
  const hasIncomingFks = schema.relations.some(r => r.toTableId === table.id);

  return !hasWorkspaceRef && !hasIncomingFks && table.name !== 'users';
}

function generateSelfAccessPolicies(tableName: string): string[] {
  return [
    `drop policy if exists "${tableName}_select_self" on public.${tableName};`,
    `create policy "${tableName}_select_self"`,
    `on public.${tableName}`,
    `for select`,
    `to authenticated`,
    `using (id = auth.uid());`,
    '',
    `drop policy if exists "${tableName}_update_self" on public.${tableName};`,
    `create policy "${tableName}_update_self"`,
    `on public.${tableName}`,
    `for update`,
    `to authenticated`,
    `using (id = auth.uid())`,
    `with check (id = auth.uid());`,
    '',
    `drop policy if exists "${tableName}_insert_self" on public.${tableName};`,
    `create policy "${tableName}_insert_self"`,
    `on public.${tableName}`,
    `for insert`,
    `to authenticated`,
    `with check (id = auth.uid());`,
    '',
  ];
}

function generateReadOnlyPolicies(tableName: string): string[] {
  return [
    `drop policy if exists "${tableName}_read_authenticated" on public.${tableName};`,
    `create policy "${tableName}_read_authenticated"`,
    `on public.${tableName}`,
    `for select`,
    `to authenticated`,
    `using (true);`,
    '',
  ];
}

function generateStandardPolicies(tableName: string, accessExpr: string): string[] {
  const roleExpr = accessExpr.replace('is_workspace_member', 'has_workspace_role')
    .replace(')', ", array['owner','admin','editor'])");
  const adminExpr = accessExpr.replace('is_workspace_member', 'has_workspace_role')
    .replace(')', ", array['owner','admin'])");

  return [
    `drop policy if exists "${tableName}_select_member" on public.${tableName};`,
    `create policy "${tableName}_select_member"`,
    `on public.${tableName}`,
    `for select`,
    `to authenticated`,
    `using (`,
    `  ${accessExpr}`,
    `);`,
    '',
    `drop policy if exists "${tableName}_insert_editor" on public.${tableName};`,
    `create policy "${tableName}_insert_editor"`,
    `on public.${tableName}`,
    `for insert`,
    `to authenticated`,
    `with check (`,
    `  ${roleExpr}`,
    `);`,
    '',
    `drop policy if exists "${tableName}_update_editor" on public.${tableName};`,
    `create policy "${tableName}_update_editor"`,
    `on public.${tableName}`,
    `for update`,
    `to authenticated`,
    `using (`,
    `  ${roleExpr}`,
    `)`,
    `with check (`,
    `  ${roleExpr}`,
    `);`,
    '',
    `drop policy if exists "${tableName}_delete_admin" on public.${tableName};`,
    `create policy "${tableName}_delete_admin"`,
    `on public.${tableName}`,
    `for delete`,
    `to authenticated`,
    `using (`,
    `  ${adminExpr}`,
    `);`,
    '',
  ];
}

// ──────────────────────────────────
// Helper utilities for IMPORT
// ──────────────────────────────────

function guessColumnType(colName: string): FieldType {
  if (colName === 'id') return 'uuid';
  if (colName.endsWith('_id')) return 'uuid';
  if (colName.endsWith('_at')) return 'timestamptz';
  if (colName.endsWith('_date')) return 'date';
  if (colName.startsWith('is_') || colName.startsWith('has_')) return 'boolean';
  if (colName === 'role' || colName === 'status' || colName === 'type') return 'text';
  if (colName === 'email') return 'varchar';
  if (colName === 'name' || colName.endsWith('_name')) return 'varchar';
  if (colName.endsWith('_url')) return 'text';
  if (colName.endsWith('_count') || colName === 'count') return 'integer';
  if (colName === 'metadata' || colName === 'config' || colName === 'settings') return 'jsonb';
  if (colName === 'amount' || colName === 'price' || colName === 'cost') return 'decimal';
  return 'text';
}

function guessReferencedTable(colName: string, tableNames: string[]): string | undefined {
  const baseName = colName.replace(/_id$/, '');

  // Direct match: brand_id → brands
  const plural = baseName + 's';
  if (tableNames.includes(plural)) return plural;
  if (tableNames.includes(baseName)) return baseName;

  // Compound names: owner_user_id → users, content_item_id → content_items
  const parts = baseName.split('_');

  // Try progressively shorter suffixes: content_item → content_items
  for (let i = 1; i < parts.length; i++) {
    const suffix = parts.slice(i).join('_');
    const suffixPlural = suffix + 's';
    if (tableNames.includes(suffixPlural)) return suffixPlural;
    if (tableNames.includes(suffix)) return suffix;
  }

  // Fuzzy match: check if any table name contains the base or vice versa
  for (const tn of tableNames) {
    const tnSingular = tn.replace(/s$/, '');
    if (tn.includes(baseName) || baseName.includes(tnSingular)) {
      return tn;
    }
  }

  return undefined;
}
